#!/usr/bin/env bash

# to initiate run $ chmod u+x scratch-bash.sh
# to actually execute: $ bash scratch-bash.sh

# to dump data
# sfdx automig:dump --u <usrname> --f automig-supplychain.json

# get alias from user 
echo "name your sustainability scratch org:"
read sname

echo "your org is $sname"
echo creating your scratch org... 
sfdx force:org:create -f config/project-scratch-def.json -s -a $sname

# install 1.11.0.5
sfdx force:package:install -p 04t3k000001qBJ3AAM -w 20 

### PSL/Perms 
# using shane's plugins https://github.com/mshanemc/shane-sfdx-plugins

sfdx shane:user:psl -l User -g User -n sustain_app_SustainabilityCloudPsl
sfdx shane:user:psl -l User -g User -n InsightsInboxAdminAnalyticsPsl

sfdx force:user:permset:assign -n SustainabilityAnalytics
sfdx force:user:permset:assign -n SustainabilityAppAuditor
sfdx force:user:permset:assign -n SustainabilityAppManager
sfdx force:user:permset:assign -n SustainabilityCloud

### loading
# configs 
sfdx force:source:push 

# data
sfdx automig:load -d demo-data -m RecordType:DeveloperName,sustain_app__EmissionFactorScope3__c:Name

### EA stuff
# make the EA dashboards populate correctly 
#sfdx shane:user:permset:assign -l User -g Integration -n SustainabilityAnalytics
#create EA apps
#sfdx analytics:app:create -m Sustainability  
#sfdx analytics:app:create -m Sustainability_Audit -a 

# open the org 
echo "open sesame..."
sfdx force:org:open